### ISSUE TITLE
[Lua datamodel] How to register custom function in LuaDataModel?

### ISSUE THREAD

**Issue by alexzhornyak** [tklab-tud/uscxml#114] opened 2017-04-26 16:22 UTC
Hello, what is the way to register custom function in LuaDataModel?

For now, I'm doing in the next way:
1) declare LuaDataModel with USCXML_API macro
2) move member `lua_State* _luaState` to public section
3) inherit from LuaDataModel
4) register this new datamodel in Factory

```
class LuaDataModelEx : public LuaDataModel {
public:
	LuaDataModelEx() {};

	std::shared_ptr<DataModelImpl> LuaDataModelEx::create(DataModelCallbacks* callbacks) {

		std::shared_ptr<DataModelImpl> dm = LuaDataModel::create(callbacks);

		lua_State *L = dynamic_cast<LuaDataModel*>(dm.get())->_luaState;

		lua_pushcfunction(L, GetSomeResult);
		lua_setglobal(L, "GetSomeResult");			

		return dm;
	}

	virtual std::list<std::string> getNames() {
		std::list<std::string> names;
		names.push_back("lua_ex");
		return names;
	}

	static int LuaDataModelEx::GetSomeResult(lua_State * L) {
		lua_pushinteger(L, 55555);
		return 1;
	}
};
```

So, my question is how to do it in more gentle way?

**Comment by sradomski** [comment] 2017-04-26 16:33
We used to have DataModelExtensions to expose data, but it is unavailable for functions as it eventually may pass language bindings and is currently unmaintained. Your approach does sound perfectly applicable, you would only need to inherit from LuaDataModel and register at the Factory to overwrite the existing prototype (no need for lua_ex). Why are you moving the `_luaState` into public though? It is a protected member and available to derived classes.

**Comment by sradomski** [comment] 2017-04-26 19:37
I will close this unless there is a feature request hidden in here somewhere :D

**Comment by alexzhornyak** [comment] 2017-04-27 07:45
I will explain why I am moving to public. Because create function is written in such way that I have no opportunity to create LuaDataModelEx actually. That's why by overriding this create function I am still creating LuaDataModel object.

So I offer to transform LuaDataModel class, something like this:
[LuaDataModel.cpp](https://github.com/tklab-tud/uscxml/files/960836/LuaDataModel.cpp.txt)
[LuaDataModel.h](https://github.com/tklab-tud/uscxml/files/960837/LuaDataModel.h.txt)

After that I will be able to correctly initialize my LuaDataModelEx object
```
class LuaDataModelEx : public LuaDataModel {
public:
	LuaDataModelEx() {};

	std::shared_ptr<DataModelImpl> LuaDataModelEx::create(DataModelCallbacks* callbacks) {

		std::shared_ptr<LuaDataModelEx> dm(new LuaDataModelEx());

		dm->doCreate(callbacks);

		lua_pushcfunction(dm->luaState_, GetSomeResult);
		lua_setglobal(dm->luaState_, "GetSomeResult");			

		return dm;
	}

	static int LuaDataModelEx::GetSomeResult(lua_State * L) {
		lua_pushinteger(L, 55555);
		return 1;
	}
};
```

**Comment by sradomski** [comment] 2017-04-27 08:59
Hmm, I can reproduce and the issue is that you cannot initialize the parent class because its create function, which is responsible, returns a shared_ptr to a new instance. This will require some refactoring, e.g., introducing init() and moving all the initialization from create to init. It's somewhat more elaborate and I'll postpone this until the weekend.

**Comment by sradomski** [comment] 2017-05-10 20:47
This is way easier now. Have a look at test-extensions.cpp and the [ExtendedLuaDataModel.h](https://github.com/tklab-tud/uscxml/blob/master/contrib/src/uscxml/ExtendedLuaDataModel.h).

**Closed by sradomski** 2017-05-10 20:47 UTC
