### ISSUE TITLE
Access violation after long period when state machine is expecting for an event

### ISSUE THREAD

**Issue by alexzhornyak** [tklab-tud/uscxml#131] opened 2017-05-17 13:29 UTC
Hello, this bug has been excruciating me for a long period of time. I was not able to correctly catch it, so hadn't opened an issue before. But finally I understood how reproduce it.

The explanation of bug:
1) this happens with difficult scxml that contains a couple of invoking sessions
2) we have scxml code of continuous working device
3) after the time when user finishes enque events in some period of time application crashes with access violation
The period of time, when application crashes, is not consistent and can be as a couple of minutes or as a couple of hours (regularity is not detected). Even sometimes it may work without exceptions. But not less than 80% of unsuccessful attempts

I prepared special scxml for detecting it. [Source code is here](https://github.com/alexzhornyak/SCXML-tests/tree/master/ContinuousWorkingDevice)

Steps to reproduce:
1) MSVC 2013 or MSVC 2015 Win 7 SP1
2) Version of uscxml dated on May 14, 2017
3) compile uscxml as shared libs
4) start **uscxml-browser** with passing **ContinuousWorkingDevice/main.scxml** . You need all folder **ContinuousWorkingDevice** because it contains nested scxmls!
5) be patient to wait, because it may happen in undefinite time

Catched variants of crash:
1) Duration 7min20sec to crash
![duration_7_20](https://cloud.githubusercontent.com/assets/18611095/26155771/01486b32-3b1d-11e7-9ece-47382d88168d.png)

2) Duration 38min02sec to crash
![duration_38_02](https://cloud.githubusercontent.com/assets/18611095/26155918/70845ce0-3b1d-11e7-8b15-c66e4a4f8ecc.png)

3) Duration 116min56sec to crash
![2017-05-17 08 53 34](https://cloud.githubusercontent.com/assets/18611095/26156082/d95c60c8-3b1d-11e7-94e5-6f71c6564ac9.png)

**Comment by alexzhornyak** [comment] 2017-05-17 13:39
More screenshots for better understanding where it happens
![2017-05-17 16 37 29](https://cloud.githubusercontent.com/assets/18611095/26156506/3c5b8c70-3b1f-11e7-8084-4b65c98f4f07.png)

![2017-05-17 16 36 06](https://cloud.githubusercontent.com/assets/18611095/26156519/43b85a66-3b1f-11e7-857a-6476f2b95b19.png)

![2017-05-17 16 35 27](https://cloud.githubusercontent.com/assets/18611095/26156529/49f139ac-3b1f-11e7-8c58-0d35e5fea958.png)

**Comment by sradomski** [comment] 2017-05-18 14:20
There used to be an issue wherein the interpreter would crash spectacularly when it was deallocated while calling a [monitor callback](https://github.com/tklab-tud/uscxml/blob/master/src/uscxml/interpreter/InterpreterMonitor.h). The issue is that the callbacks will receive a facade with a `std::shared_ptr` to the implementation, this will increase the reference count and the implementation would only be deallocated once the implementation itself returned from the monitor callback. I.e. we were in essence calling `delete this` with the destructor of the `std::shared_ptr` attached to the facade that we passed into the monitors.

What makes the issue somewhat more weird is that all your examples, consistently, crash in a rather arbitrary boost library. I will try to reproduce.

**Comment by alexzhornyak** [comment] 2017-05-19 06:04
I have good news: blocking step in invokers (with latest fix of #132) solve the problem.
14 hours of stable work :)
![2017-05-19 09 01 00](https://cloud.githubusercontent.com/assets/18611095/26235179/2117f47c-3c72-11e7-813f-4e3e8f020e31.png)

**Comment by sradomski** [comment] 2017-05-19 07:50
I could reproduce with clang/llvm on MacOS - even with a working wait_until(). I even segfault at the same line in the mersenne twister.

**Comment by alexzhornyak** [comment] 2017-05-19 08:33
It's good that you understands what happens. Because this bug drunk a lot of my blood

**Comment by sradomski** [comment] 2017-05-19 09:09
I updated the boost library in `contrib/boost` and protectd the `uuidGen` with a mutex. I am not completely satisfied that this solves the root cause, but I'd like to close this issue and wait for it to pop up again.

**Closed by sradomski** 2017-05-19 09:09 UTC
